[project]
name = "perfectunion"
version = "0.1.0"
requires-python = "~=3.14.0"
dependencies = [
    "flask",
    "flask-limiter",
    "gunicorn",
    "num2words",
    "pandas",
    "pyarrow",
    "us",
]

[dependency-groups]
dev = [
    "python-dotenv",
]

[tool.uv]
package = false
default-groups = "all"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[tool.ruff]
fix = true

[tool.ruff.lint]
extend-select = ["I"]
unfixable = ["F401"]
